#include <iostream>

using namespace std;

float staz = 0, pensja = 1000;

void PoRoku(float &staz, float &pensja) {
    staz++;
    pensja = pensja *1.1f;
}

int main()
{
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    PoRoku(staz, pensja);
    cout << "Staz: " << staz;
    cout << "\nPensja: " << pensja;
}
